server:
  port: 9000  # 后端服务器端口

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cbank?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
mybatis-plus:
  # sql文件映射地址
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.cbank.entity

Logging:
  level:
    com.wms: debug

