
server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql


Logging:
  level:
    com.wms: debug